---
- name: setup tomcat
  hosts: webservers
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Ubuntu
    apt:
      name: java
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat8 ( .tar.gz link from google)
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
      dest: /opt

  - name: extracting tar.gz file
    unarchive:
      src: /opt/apache-tomcat-8.5.83.tar.gz
      dest: /opt
      remote_src: yes

  - name: changing permission
    file:
      path: /opt/apache-tomcat-8.5.83/bin/startup.sh
      mode: 0777

  - name: Starting tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.83/bin
